version: '3.8'
services:
  community-manager:
    container_name: vtes-community-back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8080
    environment:
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: vtes-community-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${VTES_MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${VTES_MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: